<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<script language="javascript" type="text/javascript">
$(document).ready(function(){

	var id = $("#channelId").val();
	if(null != $('.subnav>li[id='+id+']').html()) {
		$('.subnav>li').removeClass('selected');
		$('.subnav>li[id='+id+']').addClass('selected');
	}
})
</script>

 <div id="conTitle">
 	<div class="navCurrent ">
 	
	<a href="/view/srplatform/portal/index.jsp" id="/view/srplatform/portal/index.jsp" title="首页" target="_self">首页</a>
	<a href="javascript:void(0)" id="/view/smallscale/business/shangquan.jsp" title="陶朱公商圈" class="cmsHref_self">陶朱公商圈</a>
	<a href="javascript:void(0)" id="/view/staticpags/sqzx/sqzx.jsp" title="商圈资讯" class="cmsHref_self">商圈资讯</a>
	<a href="javascript:void(0)" id="/view/staticpags/sqzx/ff8080812ffcb9fb013000ffc2240284.jsp" title="医疗医美行业十年修得“同船渡”" class="cmsHref_self">医疗医美行业十年修得“同船渡”</a>
		
 	</div>
 
 </div>
 
<div id="conBody">

   <input type="hidden"  id="channelId" value="ff8080812dd59be5012dda319fa70356" />
   <div class="frameNews">
    <h1>医疗医美行业十年修得“同船渡”</h1>
    <div class="subtitle"></div>
       <div class="source">
	      <span>发布时间：2011-05-18</span>
	      <span>发布人：信息时报  </span>
      </div>
      
      <p><p>&nbsp;十年前，民营医院屈指可数，十年之后，民营医院大量涌现；十年前，整形美容还是个难以启齿的话题；十年之后，整形美容散发无穷&ldquo;魔力&rdquo;；大学生为找一份好工作争相整形美容；职场中的&ldquo;白骨精&rdquo;们为增加优势也不惜下血本给力整形美容&hellip;&hellip;医疗医美行业在这十年空前发展，无论是技术领域的新进展还是行业发展的进步或乱象，都在潜移默化地影响着医生、求美者、经营者、投资者。今天，记者将医疗医美行业快速发展近十年的大事进行梳理时发现：飓风行动整治非法行医、广州首例变性人、奥美定事件、系列注射材料对整形美容初开放等事件让行业整体成长、进步、改变。我们期待，在下一个十年、二十年、三十年&hellip;&hellip;我们可以更美丽更精彩。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">医疗</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2000　颁布《中外合资合作医疗机构管理暂行办法》</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">卫生部和原外经贸部联合制定的《中外合资、合作医疗机构管理暂行办法》，规定设立的中外合资、合作医疗机构投资总额不得低于2000万元人民币；中方所占的股权比例或权益不得低于30％，外资获得可以控股的权利。《办法》的出台，为更多外资进入中国从政策层面提供了可操作空间。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">点评：俗话说，&ldquo;外来的和尚会念经&rdquo;。近年来，高端合资医院频繁进入一些大中城市取得的成绩，对国外投资者来说，这一政策意味着极大的机遇。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2001　中国开放医疗市场</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">医疗机构分类管理制度的实施，确定了营利性医疗机构的合理合法地位,在国家有关政策的扶植下，从2001年开始，我国民营医院发展迅猛,大量社会资本争先恐后地进入这个原先的投资禁区&mdash;&mdash;中国医疗市场，民营医院开始在社会上大量出现。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">点评：上个世纪80年代，民营医院已经在中国医疗行业中出现。但由于中国对医院实行国有管理，公立医院由当地卫生部门直接管理。虽然政策没有限制民营医院的建立，但卫生部门出于对公立医院的保护，在审批时对民营医院卡得很严，民营医院在这样的环境下，很难得到发展。因此2001年民营医院真正迎来了春天。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2003　政府鼓励民资进入医疗市场</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">由于公立医院资金投入不足，地方政府将医疗资金的投入来源转向了民间资本。许多地方政府改革卫生医疗体制，允许公立医院通过委托经营、股份合作、股份制等形式，或整体出让的办法，引进社会资本，并对民营医院实行3年免税制度。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">记者点评：在2003年前，营利性医院将面对营业税、城市维护建设税、教育费附加税、<a target="_blank" style="text-decoration: none; color: rgb(0, 66, 118); line-height: 24px; font-weight: bold; " href="http://house.ifeng.com/special/fangchanshui2010/">房产税</a>、城镇土地使用税、车船使用税、印花税和企业所得税等10多项税费负担。税收比例远远超过了结余的比例。也就是说，营利性医疗机构干一年，还不够给工商、税务部门缴纳各种税费的钱。而在2003年，民营医院的发展进入了最好的时期。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2005　飓风行动整治非法行医</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2005年9月，国家卫生部、公安部等七部委联合开展打击非法行医专项斗争的&ldquo;飓风行动&rdquo;，打击借助虚假宣传招摇撞骗、未经审批擅自从事性病诊疗等行为，重点打击一些公立的医疗机构聘用没有行医执照的非医务人员，通过出租科室、出租诊室、合资租用设备等方式来牟利。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">记者点评：非法行医行为严重威胁人民群众的身体健康和生命安全，&ldquo;飓风行动&rdquo;的开展，让很多医疗经营者们重新审视当前的经营模式，不少经营者也是在这个时候从承包科室转向经营医院。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2008　加强医疗广告管理</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2008年是修订后的《医疗广告管理办法》公布实施的第二年，这一年卫生部门严厉打击发布虚假违法医疗广告的行为，联合相关部门对发布涉&ldquo;性&rdquo;非法医疗广告的行为进行集中打击。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">点评：广州地区也有多家民营医疗机构因发布虚假违法医疗广告而被查处：广州市康泰专门诊部妇科、皮肤科，仁心医疗门诊部妇科、中医科，养和医疗门诊部中医内科三家广州当地的民营医疗机构被吊销诊疗科目；广州市康泰专科门诊部停业整顿1个月。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">在此之前，民营医院吸引患者的方式几乎都是广告，普遍存在夸大虚假成分。这次严厉的查处，无疑引发了一场行业地震，使经营者们认识到依靠广告存在极大的经营风险，民营医院必须把诚信建设提上经营最高战略目标，才能实现纵向或横向的深度或大范围市场扩张。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2009　新医改提高民营医院地位</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2009年1月21日，国务院审议并原则通过《医改意见》和《2009-2011年医改实施方案》，明确今后3年的阶段性工作目标，重点抓好基本医疗保障制度等五项改革，初步测算，3年内各级政府预计投入8500亿元。新医改明确提出民营医院在基本医疗定点、科研立项、职称评定、继续教育等方面与公立医院享有同等待遇；在服务准入、监督管理等方面一视同仁；积极引导社会资金以多种方式参与公立医院改制重组，适度降低公立医疗机构比重等等。新医改充分体现了多元化办医格局，明显提高了民营医院的地位。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">记者点评：新医改鼓励民营医疗机构发展，同时也加强了对民营医疗机构的监督管理。政府可以通过引导和规范，让一些质量好、服务优的民营医院，加入城镇医保体系和新兴农村合作医疗，使病人有更多的选择。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">首家公立医院转民营</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">原属于国营单位的广东省建筑中心医院经广东省卫生厅批准，2009年转为民营医院，更名为广州民生医院。这是新医改方案公布后，广州市首家由公立医院改制而来的民营医院。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">点评：建筑医院的改制成功，是新医改实施方案中将部分公立医院转为民营医院政策的落实。之前这一政策曾在社会舆论界掀起轩然大波。医院经营者张世平表示，政府如要吸引更多投资者加入医疗领域，应该从政策上真正做到一视同仁，在医保、公医准入、财政和税收政策上给予民营医疗机构同等待遇。而类似建筑医院这样长期亏损的公立医院，原医院的员工和高层的反对是最大的阻碍。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">爱尔眼科上市</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2009年10月30日，爱尔眼科作为首家民营医院登陆A股市场。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">点评：爱尔眼科的第一家医院于2001年在沈阳市和平区人民医院几百平方米的三楼成立，2003年成立的长沙爱尔眼科医院有限公司于2007年变更设立为股份有限公司，在短短几年时间内，该公司发展成为我国规模最大、发展速度最快的眼科医疗机构之一。爱尔眼科的发展轨迹绝对遵循民营医疗的发展规律，同时突破了民营医疗的发展规律，创新了经营模式，找到了正确的赢利点，成为医疗连锁发展的一个典型。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">广东省出台民营医疗机构发展意见</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2009年12月22日，广东省府办公厅即发布了《关于加快广东省民营医疗机构发展的意见》，支持民营医疗机构加快发展。广东省为此提出了力争用3年左右时间，使民营医疗机构实际床位、门诊服务量均达到全省总量的15%左右的目标。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">点评：在广东省政府大力扶持非公立医疗服务机构的利好政策下，广州市非公立医院如雨后春笋般成长。这为社区医疗服务网络建设和医疗资源配置渐趋合理奠定了基础，为市民选择&ldquo;就近性就医&rdquo;创造了可能的条件。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2010　多点执业试点</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">作为&ldquo;新医改&rdquo;的重要工作部署《广东省卫生厅关于医师多点执业的试行管理办法》2010年试行，广东省作为全国唯一省级试点，2010年1月1日起开展医师多点执业试点工作，符合条件的副主任职称以上医师，将可申请在广东省地域范围内多点执业。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">点评：&ldquo;人才&rdquo;是民营医院其中一个难题，医师多点执业就是允许医师&ldquo;主动受聘&rdquo;，也就是允许医师自主选择第二、第三执业地点。医院的专家到民营医院执业，可带动民营医院医生技术水平的提高，医院的医疗水平就能得到提升。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">发改委发布鼓励社会办医细则</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">发改委发布《关于进一步鼓励和引导社会资本举办医疗机构的意见》，一是放宽社会资本举办医疗机构的准入范围；二是进一步改善社会资本举办医疗机构的执业环境；三是促进非公立医疗机构持续健康发展。三个方面阐述了新的鼓励社会办医的大政方针。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">点评：文件放宽了社会资本办医的审批途径；明确了社会办医人才队伍稳定的一系列长远发展的保障政策，利于其快速发展壮大；对社会办医符合政策导向的业务给予同公立医院的同等待遇；税收方面，免除社会办盈利性医院的营业税，属于实质性的利好。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">医美</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2003　中国第一人造美女郝璐璐</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2003年，郝璐璐在北京一间整形医院进行全面整形手术&mdash;&mdash;做双眼皮、除眼袋、隆鼻子、大小腿吸脂、腰部吸脂、提臀、脖子吸脂、去皱、隆胸等十几个项目，并公开自己的经历，成为国内第一个公开自己整容过程的&ldquo;人造美女&rdquo;，被称为&ldquo;中国第一人造美女&rdquo;。随后半年，上海、沈阳、<a target="_blank" style="text-decoration: none; color: rgb(0, 66, 118); line-height: 24px; font-weight: bold; " href="http://app.travel.ifeng.com/city_detail_415">昆明</a>、深圳也开始运作自己的&ldquo;第一人造美女&rdquo;，手术费用从上万元到百万元不等。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">点评：&ldquo;人造美女&rdquo;让中国传统审美观&mdash;&mdash;&ldquo;内在美最重要，注重外表是肤浅&rdquo;这种观点受到了大大颠覆。对于人造美女们来说，社会舆论造成的心理压力可能比手术带来的身体问题更严重，但她们用自身的勇敢和美丽告诉我们，美丽不一定能永久，但可以令人生过得很精彩。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2004　　广州首例变性人杨柳</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2004年12月8日，32岁的湖北荆门人杨柳在广州曙光整形美容医院进行了丰胸及改脸形的首期手术，迈开做女人的第一步。杨柳先天同时具有男、女两性生殖器官的身体。10岁那年，她被查出染色体为XY，做了第一次变性手术，成为男儿身，但不成功的变性手术让杨柳忍受了二十多年病痛的折磨。其后在广州做了三期变性手术，2005年1月21日，杨柳做完脸部彩光嫩肤后，已然成为一个自信与快乐的美女。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">点评：虽然杨柳并不具备真正意义上女人的生理功能，但她说不感到遗憾，&ldquo;任何决定都是需要付出代价的，当我决定要做手术的时候，我已经接受这种缺陷。只是希望朋友们能理解我的决定，从今天起，把我当成一个真正的女人。&rdquo;破茧成蝶，杨柳用短暂的痛苦，换回了美好生活的开始。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2005 第八次全国整形外科学术会议在穗召开</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2005年5月5～8日，由广东省医学会和南方医科大学南方医院共同承办的第八次全国整形外科学术会议在广州市召开。包括港、澳、台地区以及英国、日本、印尼、日本、瑞士和美国等国整形界的专家、学者共近1000人出席了会议。会议期间，海内外的专家教授呈献了5个特邀报告、20个大会报告和170多个专题报告，涵盖了整形外科基础研究和临床应用的各个领域，展示了国内外整形外科及相关学科发展的最新研究成果。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">点评：与会代表对此次会议的组织、接待、会务、学术、会展等各项工作给予了高度评价，谓之&ldquo;一次空前的整形外科学盛会&rdquo;、&ldquo;国际性的学术会议&rdquo;。此次会议是我省历来举办的最高规格、最大规模的整形外科学术会议。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2006　奥美定事件 违规注射物充斥美容市场</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2006 年1月4日，国家药品不良反应监测中心数据显示，从2002年到2005年11月，共收到注射一种名叫&ldquo;聚丙烯酰胺水凝胶&rdquo;（即奥美定）引发的炎症、感染、硬结、团块、质硬、变形、移位等各种不良反应报告183例。在一片质疑声中，2006年的4月30日，国家药监局终于下发了全面停止奥美定的生产、销售和使用的禁令。然而，据不完全统计，已经有30万求美者注射了奥美定。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">点评：奥美定事件是中国整容界的一大噩梦，求美者为此也付出了惨痛的代价。临床证明，奥美定注射入人体以后，随着时间的推移，有一部分会降解为有毒单体，侵蚀溶解肌肉、乳腺的组织，严重者直接面临乳房切除的危险。为遏制灾难事件的蔓延，在将近十年的时间里，我们成立&ldquo;奥美定注射物取出中心&rdquo;及专项救治基金，对受害女性进行临床救治。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2007　信息时报倡导&ldquo;走向主流&rdquo;系列活动展开</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">在一系列负面事件影响下，整形美容行业诚信度在民众心中持续走低，《信息时报》在本年度发起了&ldquo;走向主流&rdquo;的倡导，号召广州整形美容行业品牌形象的主流机构主动站出来，展示自身的诚信风采。活动包括&ldquo;广东诚信整形美容机构品牌联展&rdquo;、&ldquo;粤整形美容界主流力量高峰论坛2007&rdquo;、&ldquo;2007广东整形行业年度评选&rdquo;三大部分。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">点评：系列活动得到了业界的高度认可和赞誉，引起了读者的热切关注。我们看到广东整形业界表现出令人欣喜的变化：大规模民营医疗美容机构稳扎稳打，进一步往品牌化建设方向发展，小规模整形机构在进一步自我规范中建立自己的经营特色，稳步向前，重新树立行业的形象。与此同时，民营机构投入自身资源，主动承担社会公民责任，参与更多的社会公益活动，造福社会。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2008　民营机构首次承办广东整形界学术会议</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">4月11日～13日，广东省医学会第四届整形外科分会第六次全体委员会议召开，本次会议是由广东省医学会主办、美莱医学美容集团、南方医院协办，其也成为首次有民营整形机构协办的整形学术会议。广东省整形外科学分会主任委员、南方医院整形美容外科主任高建华教授指出，整形外科学术会议除了是学术界进行技术交流的会议，还承担另一个责任，那就是希望通过正规的、科学的、现代的学术会，来引导整个学界的发展。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">点评：以前广东整形外科分会历次的学术会议由各大公立医院承办，本次会议第一次由民营机构进行承办，因为民营机构对于广东整形外科行业发展占有越来越重要的地位，整个市场的发展，也离不开民营机构的配合和协作。这次会议成为公立医院和民营机构经常合作的模式，使两者之间更好地协调相处，从而有利于整形界发展，有利于提高广东整形美容界的和谐。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2009　系列注射材料对整形美容初开放</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">3月信息时报记者独家获悉，A型肉毒毒素保妥适（BOTOX）正式获得中国国家食品药品监督管理局（SFDA）的批准，用于暂时性改善65岁及以下成年患者由于皱眉肌或降眉间肌活动造成的中到重度皱眉纹。6月，获批的注射填充项目玻尿酸（瑞蓝2）开始在各大城市登陆，它以填充物的方式注射进入真皮皱折凹陷，或通过丰润部位达到除皱纹与修饰脸部的效果。9月和10月，SFDA又相继通过双美I号（胶原蛋白植入剂）以及EME逸美（医用羟丙基甲基纤维素-透明质酸钠溶液）两个新的面部填充材料。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">点评：注射类整形美容项目成为这两年整形美容业界最热门的关键词，无创、微创、非手术&hellip;&hellip;等不同的名称，代表的都是整形美容未来发展的方向。不过，无论项目如何简单、有效、安全，作为求美者要寻找有资质和有经验的整形医生去进行注射，保存好产品的外包装、编号、标签等有关数据。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2010　王贝整形事件蒙阴影</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">2010年11月15日，王贝母女走进了武汉某整形医院，接受面部磨骨手术（颧骨、下颌角）。在王贝进行下颌角手术过程中，出现了意外，怀疑因为手术部位大出血，血液通过王贝喉部进入气管，造成窒息，经转院抢救无效后于当天下午死亡。事件引起轩然大波，不仅让公众对王贝死亡原因倍感困惑，也对整形美容行业产生了种种责问，所谓的行业乱象、黑幕被广泛报道，求美者的信心受到直接的打击，特别是涉及颌面骨的整形手术，更是乏人问津。</p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 25px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; line-height: 24px; text-indent: 28px; font-size: 14px; color: rgb(43, 43, 43); font-family: 宋体, arial, helvetica, clean, sans-serif; ">点评：爱美是人的天性，通过现代医学技术改变自己的外貌以提升自身的总体素质，改变自己的自卑或不满的心理，如此做法是无可厚非的。但对整形美容不应该抱有&ldquo;很容易&rdquo;的想法，这是外科手术、有风险、有恢复时间，这些是术前必须认识和了解的。行业机构更应该以此为鉴，将工作重点放在医疗质量和服务水平上，向良性、健康的方向发展。</p>
</p>
   </div>
   
 </div>

