/*
Source Server         : srplatform
Source Server Version : SVN-1595
Source Host           : 192.168.2.10
Source Database       : srplatform
Target Server Type    : DB2
Date: 2010-02-26 17:50:00
*/

--角色冲突
DROP TABLE AUTH_CONFLICT_ROLE;

--数据资源
DROP TABLE AUTH_DATA_RES_TYPE;

DROP TABLE AUTH_GADGET;

--菜单
DROP TABLE AUTH_MENU;

--组织机构
DROP TABLE AUTH_ORGNIZATION;

--组织规则
DROP TABLE AUTH_ORGNIZATION_RULE;

--机构详细信息
DROP TABLE AUTH_ORG_DETAIL;

--员工
DROP TABLE AUTH_ORG_EMPLOYEE;

--机构组织类型
DROP TABLE AUTH_ORG_STRU_TYPE;

--角色资源
DROP TABLE AUTH_ROLE_RESOURCE;

--角色
DROP TABLE AUTH_ROLE;

--角色扩展信息
DROP TABLE AUTH_ROLE_EXTEND;

--资源
DROP TABLE AUTH_RESOURCE;

--用户
DROP TABLE AUTH_USER;

DROP TABLE AUTH_USER_GADGET;

--用户角色
DROP TABLE AUTH_USER_ROLE;

--附件
DROP TABLE BASE_ATTACHMENT;

--字典
DROP TABLE BASE_DICTIONARY;

--字典类型
DROP TABLE BASE_DICTIONARY_TYPE;

--区域
DROP TABLE BASE_DISTRICT;

--行业
DROP TABLE BASE_INDUSTRY;

--登录日志
DROP TABLE BASE_LOGIN_LOGS;

--操作日志
DROP TABLE BASE_OPER_LOGS;

--序列号
DROP TABLE BASE_SEQUENCE_NUMBER;

DROP TABLE BASE_SYSCONFIGITEM;

DROP TABLE BASE_SYSCONFIGITEM_VALUE;

DROP TABLE BASE_SYSCONFIG_PRE_VALUES;

DROP TABLE BASE_SYSCONFIG_TYPE;

DROP TABLE DEMO_ADDITIONAL;

DROP TABLE DEMO_AREA;

DROP TABLE DEMO_BRAND;

DROP TABLE DEMO_GOODS;

DROP TABLE DEMO_GOODS_CLASS;

DROP TABLE DEMO_GOODS_ORDER;

DROP TABLE DEMO_GOODS_PARAM;

DROP TABLE DEMO_OPTION;

DROP TABLE DEMO_ORDER;

DROP TABLE DEMO_PURCHASE_CATEGORY;

--组织类型字典
DROP TABLE ORG_ROLE;

--组织机构中使用，代表员工
DROP TABLE ORG_EMPLOYEE;

DROP TABLE JBPM4_DEPLOYMENT;

DROP TABLE JBPM4_DEPLOYPROP;

DROP TABLE JBPM4_EXECUTION;

DROP TABLE JBPM4_HIST_ACTINST;

DROP TABLE JBPM4_HIST_DETAIL;

DROP TABLE JBPM4_HIST_PROCINST;

DROP TABLE JBPM4_HIST_TASK;

DROP TABLE JBPM4_HIST_VAR;

DROP TABLE JBPM4_ID_GROUP;

DROP TABLE JBPM4_ID_MEMBERSHIP;

DROP TABLE JBPM4_ID_USER;

DROP TABLE JBPM4_JOB;

DROP TABLE JBPM4_LOB;

DROP TABLE JBPM4_PARTICIPATION;

DROP TABLE JBPM4_PROPERTY;

DROP TABLE JBPM4_SWIMLANE;

DROP TABLE JBPM4_TASK;

DROP TABLE JBPM4_VARIABLE;