<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<script language="javascript" type="text/javascript">
$(document).ready(function(){

	var id = $("#channelId").val();
	if(null != $('.subnav>li[id='+id+']').html()) {
		$('.subnav>li').removeClass('selected');
		$('.subnav>li[id='+id+']').addClass('selected');
	}
})
</script>

 <div id="conTitle">
 	<div class="navCurrent ">
 	
	<a href="/view/srplatform/portal/index.jsp" id="/view/srplatform/portal/index.jsp" title="首页" target="_self">首页</a>
	<a href="javascript:void(0)" id="/view/staticpags/zzbjyctwh/zzbjyctwh.jsp" title="诸子百家与传统文化" class="cmsHref_self">诸子百家与传统文化</a>
	<a href="javascript:void(0)" id="/view/staticpags/bjxxjh/bjxxjh.jsp" title="百家思想精华" class="cmsHref_self">百家思想精华</a>
	<a href="javascript:void(0)" id="/view/staticpags/bjxxjh/ff8080812ee243a4012ee282ddfc01d7.jsp" title="法家这么说" class="cmsHref_self">法家这么说</a>
		
 	</div>
 
 </div>
 
<div id="conBody">

   <input type="hidden"  id="channelId" value="ff8080812ed7f020012ee0caa13d09a3" />
   <div class="frameNews">
    <h1>法家这么说</h1>
    <div class="subtitle"></div>
       <div class="source">
	      <span>发布时间：2011-03-23</span>
	      <span>发布人：高路  </span>
      </div>
      
      <p><p class="MsoNormal" style="margin: 0cm 0cm 0pt"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" align="center" style="text-align: center; margin: 0cm 0cm 0pt">&nbsp;</p>
<p class="MsoNormal" align="center" style="text-align: center; margin: 0cm 0cm 0pt"><b style="mso-bidi-font-weight: normal"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt"><o:p>&nbsp;</o:p></span></b></p>
<p class="ListParagraph" style="text-indent: -36pt; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0; mso-list: l0 level1 lfo1"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt; mso-bidi-font-family: 新宋体"><span style="mso-list: Ignore">1、<span style="font: 7pt 'Times New Roman'">&nbsp; </span></span></span><span style="font-family: 新宋体; font-size: 12pt">医善吮人之伤，含人之血，非骨肉之亲也，利所加也。故舆人成舆，则欲人之富贵；匠人成棺，则欲人之夭死也。非舆人仁，而匠人贼也。人不贵，则舆不售，人不死，则棺不买。情非憎人也，利在人之死也。<span lang="EN-US">----</span>韩非<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: -36pt; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0; mso-list: l0 level1 lfo1"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt; mso-bidi-font-family: 新宋体"><span style="mso-list: Ignore">2、<span style="font: 7pt 'Times New Roman'">&nbsp; </span></span></span><span style="font-family: 新宋体; font-size: 12pt">事起而有所利，其尸主之；有所害，比反察之。<span lang="EN-US">----</span>韩非<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: 0cm; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0"><span style="font-family: 新宋体; font-size: 12pt">注释：一件事情发生，如果有什么好处，一定是能够从中得到利益的人主持干的；如果有什么害处，一定要从反面去进行思考。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: -36pt; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0; mso-list: l0 level1 lfo1"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt; mso-bidi-font-family: 新宋体"><span style="mso-list: Ignore">3、<span style="font: 7pt 'Times New Roman'">&nbsp; </span></span></span><span style="font-family: 新宋体; font-size: 12pt">人无毛羽，不衣则不犯寒；上不属天而下不着地，以肠胃为根本，不食则不能活，是以不免于欲利之心。<span lang="EN-US">------</span>韩非<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: -36pt; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0; mso-list: l0 level1 lfo1"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt; mso-bidi-font-family: 新宋体"><span style="mso-list: Ignore">4、<span style="font: 7pt 'Times New Roman'">&nbsp; </span></span></span><span style="font-family: 新宋体; font-size: 12pt">夫同体一者相不可。且夫利异而害不同者，先王所以为保也。<span lang="EN-US">---</span>韩非<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: 0cm; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0"><span style="font-family: 新宋体; font-size: 12pt">注释：利益一致的人不可能相互监督，使用利害关系不同的人，是古代君王治理国家的保证。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: -36pt; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0; mso-list: l0 level1 lfo1"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt; mso-bidi-font-family: 新宋体"><span style="mso-list: Ignore">5、<span style="font: 7pt 'Times New Roman'">&nbsp; </span></span></span><span style="font-family: 新宋体; font-size: 12pt">故君臣异心。君以计蓄臣，臣以计事君。君臣之交，计也。害身而利国，臣弗为也；害国而利臣，君不行也。臣之情，害身无利；君之情，害国无亲。君臣也者，以计合者也。<span lang="EN-US">----</span>韩非<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: 0cm; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0"><span style="font-family: 新宋体; font-size: 12pt">注释：君主与臣子的心思是不同的。君主算计着蓄养臣子，臣子也算计着侍奉君主，他们之间的交往出于各自的盘算。对自己有害而对国家有利的事情，臣子是不会去做的；对国家有害而对臣子有利的事情，君主也不会去做。就臣子的本心来看，有害于自身就谈不上利益；从君主的本意来说，有害于国家就谈不上亲近。君主和臣子之间，是在算计的前提下结合起来的。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: -36pt; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0; mso-list: l0 level1 lfo1"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt; mso-bidi-font-family: 新宋体"><span style="mso-list: Ignore">6、<span style="font: 7pt 'Times New Roman'">&nbsp; </span></span></span><span style="font-family: 新宋体; font-size: 12pt">故人行事施与，以利之为心，则越人易和；以害之为心，则父子离且怨。<span lang="EN-US">----</span>韩非<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: 0cm; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0"><span style="font-family: 新宋体; font-size: 12pt">注释：人们行事和付出，若是报着与人为利的心思，即使疏远得如同越人那样陌生也容易亲和；若是抱着与人为害的心思，即使父子也会彼此疏离，互相埋怨。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: -36pt; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0; mso-list: l0 level1 lfo1"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt; mso-bidi-font-family: 新宋体"><span style="mso-list: Ignore">7、<span style="font: 7pt 'Times New Roman'">&nbsp; </span></span></span><span style="font-family: 新宋体; font-size: 12pt">凡治天下，必因人性。<span lang="EN-US">----</span>韩非<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: -36pt; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0; mso-list: l0 level1 lfo1"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt; mso-bidi-font-family: 新宋体"><span style="mso-list: Ignore">8、<span style="font: 7pt 'Times New Roman'">&nbsp; </span></span></span><span style="font-family: 新宋体; font-size: 12pt">任人者，使有势也。<span lang="EN-US">----</span>韩非<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: 0cm; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0"><span style="font-family: 新宋体; font-size: 12pt">注释：任用人，就是给他权势。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: -36pt; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0; mso-list: l0 level1 lfo1"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt; mso-bidi-font-family: 新宋体"><span style="mso-list: Ignore">9、<span style="font: 7pt 'Times New Roman'">&nbsp; </span></span></span><span style="font-family: 新宋体; font-size: 12pt">臣主之利相与异也。何以明之哉？曰：主利在有能而任官，臣利在无能而得事；主利在有劳而爵禄，臣利在无功而富贵；主利在豪杰使能，臣利在朋党用私。<span lang="EN-US">----</span>韩非<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: 0cm; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0"><span style="font-family: 新宋体; font-size: 12pt">注释：臣下和君主之间的利益是对立的。为什么这样说呢？君主的利益在于任用有能力的人来当官，而臣下的利益却在于原本无能也要得到权位；君主的利益在于把爵位和俸禄授予有功的人，而臣下的利益却在于即使没有功劳也要得到富贵；君主的利益在于使有能力的人发挥才干，而臣下的利益在于通过亲朋和同伙把持权位。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: -36pt; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0; mso-list: l0 level1 lfo1"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt; mso-bidi-font-family: 新宋体"><span style="mso-list: Ignore">10、<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><span style="font-family: 新宋体; font-size: 12pt">夫仁义者，忧天下之害，趋一国之患，不避卑辱，谓之仁义。<span lang="EN-US">----</span>韩非<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: 0cm; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0"><span style="font-family: 新宋体; font-size: 12pt">注释：所谓仁义，就是忧虑天下的祸害，奔赴国家的患难，而不顾及自己卑微的地位和屈辱的待遇，这才称得上是仁义。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: -36pt; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0; mso-list: l0 level1 lfo1"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt; mso-bidi-font-family: 新宋体"><span style="mso-list: Ignore">11、<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><span style="font-family: 新宋体; font-size: 12pt">小信成则大信立，故明主积于信。<span lang="EN-US">----</span>韩非<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: 0cm; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0"><span style="font-family: 新宋体; font-size: 12pt">注释：小事上守信用，就可以在大事上赢得信用，所以英明的君主通过信用来积累自己的声望。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: -36pt; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0; mso-list: l0 level1 lfo1"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt; mso-bidi-font-family: 新宋体"><span style="mso-list: Ignore">12、<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><span style="font-family: 新宋体; font-size: 12pt">民之于利也，若水于下也。四旁无择也。<span lang="EN-US">----</span>商鞅<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: 0cm; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0"><span style="font-family: 新宋体; font-size: 12pt">注释：民众趋利而行，就像水往低处流一样，是根本没有选择的。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: -36pt; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0; mso-list: l0 level1 lfo1"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt; mso-bidi-font-family: 新宋体"><span style="mso-list: Ignore">13、<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><span style="font-family: 新宋体; font-size: 12pt">民之性：饥而求食，老而求佚，苦则索乐，辱则求荣。此民之情也。民之求利，失礼之法；求名，失性之常。<span lang="EN-US">----</span>商鞅<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: 0cm; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0"><span style="font-family: 新宋体; font-size: 12pt">注释：人的本性是：饥饿了就去寻求食物，劳累了就要去歇息，痛苦了就追求欢乐，屈辱了就企求荣誉。因而，人在追求利益的时候，可以不顾礼法的规定；人在追求名声的时候，可以违反人情的常态。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: -36pt; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0; mso-list: l0 level1 lfo1"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt; mso-bidi-font-family: 新宋体"><span style="mso-list: Ignore">14、<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><span style="font-family: 新宋体; font-size: 12pt">民之情莫不欲生儿恶死。<span lang="EN-US">----</span>管仲<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: -36pt; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0; mso-list: l0 level1 lfo1"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt; mso-bidi-font-family: 新宋体"><span style="mso-list: Ignore">15、<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><span style="font-family: 新宋体; font-size: 12pt">凡人之情，得所欲则乐，逢所恶则忧，此贵贱之所同也。<span lang="EN-US">----</span>管仲<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: -36pt; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0; mso-list: l0 level1 lfo1"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt; mso-bidi-font-family: 新宋体"><span style="mso-list: Ignore">16、<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><span style="font-family: 新宋体; font-size: 12pt">民，利之则来，害之则去。<span lang="EN-US">----</span>管仲<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: -36pt; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0; mso-list: l0 level1 lfo1"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt; mso-bidi-font-family: 新宋体"><span style="mso-list: Ignore">17、<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><span style="font-family: 新宋体; font-size: 12pt">用赏者贵诚，用刑者贵必，刑赏信必于耳目之所见，则其所不见，莫不暗化矣。<span lang="EN-US">----</span>管仲<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: 0cm; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0"><span style="font-family: 新宋体; font-size: 12pt">注释：奖赏贵在兑现，惩罚贵在坚决。奖赏贯彻了，惩罚得到贯彻了，人们看在眼里，听到耳中<span lang="EN-US">----</span>即使没有亲眼看到也不要紧<span lang="EN-US">----</span>赏罚的威力变会潜移默化地发挥作用。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt">18</span><span style="font-family: 新宋体; font-size: 12pt">、智过万人者谓之英，千人者谓之俊，百人者谓之豪，十人者谓之杰。明与天道，察与地理，通于人情，大足以容众，德足以怀远，信足以一异，知足以知变者，人之英也。<span lang="EN-US">----</span>《淮南子》<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt">19</span><span style="font-family: 新宋体; font-size: 12pt">、提到信，人们往往笼统称之为诚信。其实这是一种误解，信与诚是两个不同的范畴。诚强调的是内心的真实，但对信来说，真心也好，假意也罢，只要是说出口的，就必须去做。当然，信中也有诚，说出的话一定要兑现，也就是真诚地对待自己的诺言。一个人可能一时做不到对别人真心，但一定要做到对自己真心。如果连这一点都做不到的话，就没人看得起他了<span lang="EN-US">------</span>谁会去尊重一个连自己都不尊重的人呢。<span lang="EN-US">------</span>高路<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt">20</span><span style="font-family: 新宋体; font-size: 12pt">、学会听人说话不是一件容易的事。<span lang="EN-US">----</span>高路<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt"><b style="mso-bidi-font-weight: normal"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt"><o:p>&nbsp;</o:p></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt"><b style="mso-bidi-font-weight: normal"><span style="font-family: 新宋体; font-size: 12pt">法家人物小传<span lang="EN-US"><o:p></o:p></span></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt"><b style="mso-bidi-font-weight: normal"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt">1</span></b><b style="mso-bidi-font-weight: normal"><span style="font-family: 新宋体; font-size: 12pt">、管仲：</span></b><span style="font-family: 新宋体; font-size: 12pt">名夷吾，字仲。春秋时期颍上（今属安徽省）人。早年经商，后被齐桓公任为卿大夫，主持齐国政局<span lang="EN-US">40</span>年。他锐意改革，兴利除弊，通货积财，把齐国治理成当时最强大的诸侯国。以强大的国力为后盾，他协助齐桓公以&ldquo;尊王攘夷&rdquo;号召天下。所谓尊王，就是拥戴已经失去实际控制力的周朝天子；所谓攘夷，就是抵御中原华夏族之外的其他族群。这个策划极为成功，不仅稳定了天下局势，而且使齐桓公以中流砥柱的形象展现在诸侯和世人的面前，成为春秋时期的第一位霸主。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt"><span style="font-family: 新宋体; font-size: 12pt">管仲有两件事最为著名。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt"><span style="font-family: 新宋体; font-size: 12pt">一件是他与鲍叔牙的关系。他俩合伙做生意，分钱时他拿得多，鲍叔牙不认为他贪心，而认为他需要钱用；管仲在战场上三番五次地逃跑，鲍叔牙不认为他胆小，而认为他有老母亲需要照顾；管仲辅佐的公子在政治上失败后，别的追随者以自杀表示气节，而管仲却选择活下来，鲍叔牙不认为他无耻，而认为他胸怀大志。相知到这个份上，真可以说是天下第一朋友。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt"><span style="font-family: 新宋体; font-size: 12pt">另一件是他与齐桓公的关系。齐桓公做公子的时候，管仲是他的对立面，辅佐的是另一位公子。为了使这位公子能够抢先登上君位，管仲半路设伏，亲自放箭射杀齐桓公，幸亏齐桓公机智，躺倒装死，才逃过一劫。但齐桓公不记私仇，反而把国家行政大权托付给管仲，使他得以成为一代名相。互信到这个份上，真可以说是天下第一君臣。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt"><span style="font-family: 新宋体; font-size: 12pt">管仲说自己是&ldquo;不羞小节，而耻功名不显与天下&rdquo;。他的功绩是出了把齐国建成当时最强大的国家外，还留下了一套治国方略。他是第一个明确提出&ldquo;依法治国&rdquo;并付之实践的人。吴起、商鞅、韩非、李斯等法家巨子正是沿着这个思路往前走的。但他又不像后来的法家那样极端和冷酷，主张在实行法治的同时，采取德制；在维护国家利益和君主地位的同时，顺应民意，爱护百姓。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt"><span style="font-family: 新宋体; font-size: 12pt">管仲的思想言论收入《管子》一书，此书为管仲的追随者所著。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt"><b style="mso-bidi-font-weight: normal"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt">2</span></b><b style="mso-bidi-font-weight: normal"><span style="font-family: 新宋体; font-size: 12pt">、吴起<span lang="EN-US"><o:p></o:p></span></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt"><span style="font-family: 新宋体; font-size: 12pt">战国时期卫国左氏（今山东曹县西北）人。曾经投入孔子的学生曾参门下学习，后放弃儒学，研读兵法韬略，走上了从政的道路。吴起曾为多个诸侯国服务。先是在鲁国为将，大败齐军，创造了以弱胜强的战绩。后来到魏国为将，出击秦国，连下五城，取到了魏国对秦国作战中最大的胜利。他又统帅<span lang="EN-US">5</span>万士卒，击溃<span lang="EN-US">50</span>万秦军，创造了兵战史上的奇迹。他来到楚国，担任令尹，主持变法，使一度陷于贫国弱兵的楚国实力大增，竟然出兵中原，打到黄河边上。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt"><span style="font-family: 新宋体; font-size: 12pt">吴起的故事很多，留给人们的印象很是另类。他功利心极强，以至于亲人都可以牺牲掉。在曾参门下时，母亲死了都不回家看看，气得曾参跟他绝了交。因为妻子没有完全按照他的要求编织一条丝带，就离弃了她；在鲁国为将时，由于妻子是鲁国的宿敌齐国人，受到怀疑，他就杀了妻子一表明自己的忠心。他心计极深，以至于死到临头都不吃亏。当那些在他的变法中受到打击的贵族们群起而攻之的时候，他竟然把身上中的箭拔下来插进楚悼王的尸身上，把射王尸的死罪扣在政敌的头上，拉上了<span lang="EN-US">70</span>多家大贵族跟他一块儿去死。母亲、妻子是至亲，楚悼王是知己，至爱亲朋都可以变成手段，还有什么不能践踏的？所以，当他极力展示人性中美的一面时，总是让人疑心背后隐藏着不可告人的目的。为了信守与熟人一起吃饭的约定，他整整饿了一天；为了减轻士兵的痛苦，他跪在地上吸吮患者的脓血<span lang="EN-US">----</span>凡此种种，谁有能相信他是真心实意的？<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt"><span style="font-family: 新宋体; font-size: 12pt">吴起留下了一步兵书，《吴起兵法》。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt"><b style="mso-bidi-font-weight: normal"><span lang="EN-US" style="font-family: 新宋体; font-size: 12pt"><o:p>&nbsp;</o:p></span></b></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt"><b style="mso-bidi-font-weight: normal"><span style="font-family: 新宋体; font-size: 12pt">商鞅</span></b><span style="font-family: 新宋体; font-size: 12pt">（约公元前<span lang="EN-US">390</span>&mdash;前<span lang="EN-US">338</span>）<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: 0cm; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0"><span style="font-family: 新宋体; font-size: 12pt">本叫公孙鞅，姓姬，公孙是他的氏，名鞅。他是卫国的庶出公子。公子就是后来人们说的王子，庶出是妾生的儿子。由于他属于公族（王族），习惯上把国名&ldquo;卫&rdquo;放在他的名字前面，称为卫鞅。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: 0cm; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0"><span style="font-family: 新宋体; font-size: 12pt">公孙鞅先到卫国谋事。其间受到一个叫公子卬的人的照应，两人情同手足。后来听说秦国招募人才，公孙鞅便只身前往。起先国君秦孝公并不看好公孙鞅，后来听了他以法家思想设计的强国之道，一下子就被迷住了。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: 0cm; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0"><span style="font-family: 新宋体; font-size: 12pt">秦孝公决定起用商鞅。经过三年的精心准备，公孙鞅被任命为左庶长，主持变法。公孙鞅认为，治国之要在于抓住三个根本，即法、信、权。法就是任法而治，以法度为最高准绳。信讲的是赏罚，所谓赏罚有信。权就是国家权力，一定要集中在君主手里。秦国的变法实际上就是围绕这三个根本展开的。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: 0cm; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0"><span style="font-family: 新宋体; font-size: 12pt">公孙鞅与吴起一样，锋芒所向直指旧制度和旧贵族，引起了旧势力极大不满，但在秦孝公的坚决支持下，他们无法阻挡新法的实施。没用几年，一个野蛮落后的秦国竟然呈现出民富国强、社会安定、兵强马壮的新气象。秦国终于有资本与各诸侯国角逐中原了。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: 0cm; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0"><span style="font-family: 新宋体; font-size: 12pt">公孙鞅被任命为大良造，这个官位是将相合一的职务，既有行政权，又有军权。这时，秦国的作战对象是横在东进路上强大的魏国。趁着魏国的庞涓被齐国的孙膑打败的机会，公孙鞅统领大军讨伐魏国。魏军的统帅正是公子卬。公孙鞅派人送信给公子</span><span style="font-family: 新宋体; font-size: 12pt; mso-bidi-font-family: 宋体">卬，建议休战，并提出见面。公子卬同意了，但他万万没有想到，正在他们两个老朋友推杯换盏的时候，埋伏的勇士一拥而上，擒住了他。失去了统帅的魏军乱作一团，十万大军遭到歼灭。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: 0cm; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0"><span style="font-family: 新宋体; font-size: 12pt; mso-bidi-font-family: 宋体">就是因为这个功劳，秦孝公把<span lang="EN-US">15</span>个城邑封给公孙鞅，人们开始叫他商君、商鞅。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: 0cm; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0"><span style="font-family: 新宋体; font-size: 12pt; mso-bidi-font-family: 宋体">秦孝公死后，新君即位，有人告他谋反，他只好带着一家老小出逃。魏国与秦国接壤，如果魏国不让他入境，他逃不出秦国。商鞅请求入境。魏国守将怀疑他耍阴谋，说：&ldquo;你连好朋友公子卬都欺骗，谁敢保证你不是在骗我呢！&rdquo;下令士兵把他赶回秦国。没有办法，商鞅只好逃回自己的封地，组织武装，这回是真的造反了。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: 0cm; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0"><span style="font-family: 新宋体; font-size: 12pt; mso-bidi-font-family: 宋体">秦军前来镇压，他只有自己的区区封地，哪里是他亲手打造的战争机器的对手？<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: 0cm; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0"><span style="font-family: 新宋体; font-size: 12pt; mso-bidi-font-family: 宋体">商鞅死后，他的弟子整理他的遗作成书《商君书》<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0pt"><b style="mso-bidi-font-weight: normal"><span style="font-family: 新宋体; font-size: 12pt; mso-bidi-font-family: 宋体">韩非（约公元前<span lang="EN-US">280--233</span>）<span lang="EN-US"><o:p></o:p></span></span></b></p>
<p class="ListParagraph" style="text-indent: 0cm; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0"><span style="font-family: 新宋体; font-size: 12pt">韩非是韩国的公子，口吃，不善言辞。最初曾经跟着儒学大师荀子学习。同学中有一位楚国青年，就是后来做到了秦国丞相的李斯。这时的儒家处于低潮，因为它的主旨与当时社会大兼并、大竞争的潮流相去甚远，就连荀子都对儒学做了一些修正，提出人性恶的观点来补充传统的人性善的思想，但其最终回归礼制的结论使韩非难以接受。于是韩非便离开荀子，回到韩国精心研读法家学问，著书立说。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: 0cm; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0"><span style="font-family: 新宋体; font-size: 12pt">韩非以广博的学识和对历史以及现实的深刻理解，在法家政治实践的基础上，综合以往法家思想精华，创立了自己一套相对完整的学说。其最大特点是把法、术、势三者结合。其中，法指的是以法治国，这是治国的根本方针；势指的是包括赏罚权在内的权位和威力，它是实行以法治国的政治基础和保证；术是计谋，基本功能是把权力用活。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: 0cm; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0"><span style="font-family: 新宋体; font-size: 12pt">韩国是战国七雄之一，但却是最弱小的，在那个被韩非称为&ldquo;争于气力&rdquo;的年代，弱小就是被宰割的代名词。他几次上书韩国君王，建议变法图强，但没人搭理他。然而，有一个人却被打动了，这人就是秦王嬴政。嬴政看了他的几个篇章，叹道：哎呀！寡人要是能够见到这个人，与他交往，就是当即死去也没有任何遗憾！于是便发兵攻打韩国。韩王没辙，只好派韩非做使者前往秦国谈判。<span lang="EN-US"><o:p></o:p></span></span></p>
<p class="ListParagraph" style="text-indent: 0cm; margin: 0cm 0cm 0pt 36pt; mso-char-indent-count: 0"><span style="font-family: 新宋体; font-size: 12pt">嬴政喜欢读韩非的书，加上韩非本人又有口吃，韩非便把自己的见解写成文章呈送秦王，中心意思是劝说秦王保留韩国，全力以赴对付赵国。韩非维护韩国的立场与嬴政横扫六国的雄心是矛盾的，是否起用韩非，嬴政犹豫不决。这时候，李斯出场了。他暗示秦王，留下韩非这个旷古奇才，对秦国是个祸患。就这样，嬴政把韩非关进了监狱。李斯派人给韩非送去了毒药，让他自杀。韩非没有办法，只好服毒自尽。韩非的理论极其严谨、透彻，但他处理现实生活的本领却不怎么样，结果死于自己的崇拜者和同窗之手。<span lang="EN-US"><o:p></o:p></span></span></p>
</p>
   </div>
   
 </div>

