<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<script language="javascript" type="text/javascript">
$(document).ready(function(){

	var id = $("#channelId").val();
	if(null != $('.subnav>li[id='+id+']').html()) {
		$('.subnav>li').removeClass('selected');
		$('.subnav>li[id='+id+']').addClass('selected');
	}
})
</script>

 <div id="conTitle">
 	<div class="navCurrent ">
 	
	<a href="/view/srplatform/portal/index.jsp" id="/view/srplatform/portal/index.jsp" title="首页" target="_self">首页</a>
	<a href="javascript:void(0)" id="/view/smallscale/business/shangquan.jsp" title="陶朱公商圈" class="cmsHref_self">陶朱公商圈</a>
	<a href="javascript:void(0)" id="/view/staticpags/mrft/mrft.jsp" title="名人访谈" class="cmsHref_self">名人访谈</a>
	<a href="javascript:void(0)" id="/view/staticpags/mrft/ff8080812e31dec9012e37879bc6014e.jsp" title="塔尔·宾－夏哈尔博士和《哈佛幸福课》" class="cmsHref_self">塔尔·宾－夏哈尔博士和《哈佛幸福课》</a>
		
 	</div>
 
 </div>
 
<div id="conBody">

   <input type="hidden"  id="channelId" value="ff8080812dd59be5012dda336f2d035e" />
   <div class="frameNews">
    <h1>塔尔·宾－夏哈尔博士和《哈佛幸福课》</h1>
    <div class="subtitle"></div>
       <div class="source">
	      <span>发布时间：2011-02-18</span>
	      <span>发布人：无  </span>
      </div>
      
      <p><p><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'"><font size="3">我们来到这个世上，到底追求什么才是最重要的？</font></span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
</span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'"><font size="3">他坚定地认为：幸福感是衡量人生的唯一标准，是所有目标的最终目标。</font></span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
</span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'"><font size="3">人们衡量商业成就时，标准是钱。用钱去评估资产和债务、利润和亏损，所有与钱无关的都不会被考虑进去，金钱是最高的财富。但是我认为，人生与商业一样，也有盈利和亏损。</font></span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
</span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'"><font size="3">具体地说，在看待自己的生命时，可以把负面情绪当作支出，把正面情绪当作收入。</font></span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
</span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'"><font size="3">当正面情绪多于负面情绪时，我们在幸福这一&ldquo;至高财富&rdquo;上就盈利了。</font></span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
</span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'"><font size="3">所以，幸福应该是快乐与意义的结合！</font></span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
<font face="Times New Roman" size="3">&quot;</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'"><font size="3">一个幸福的人，必须有一个明确的、可以带来快乐和意义的目标，然后努力地去追求。真正快乐的人，会在自己觉得有意义的生活方式里，享受它的点点滴滴。</font></span><font size="3"><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">&quot;<br />
&quot;I spent close to 30 years of my life unhappily successful. I was the Israeli national squash champion, completed my undergraduate degree at Harvard, and subsequently spent a year at beautiful Cambridge University, studying education while earning my blue in squash.<br />
More than titles and degrees, though, I desperately wanted to be happy, or at least happier than I had been. I started to study psychology in the hope of finding some answers, and it was through my studies that I realized what should have been obvious to me all along - that happiness is mostly contingent on our state of mind, rather than our status or the state of our bank account. &quot;<br />
</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">塔尔&middot;宾－夏哈尔自称是一个害羞、内向的人。</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">&quot;</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">我曾不快乐了</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">30</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">年。</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">&quot;</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">本－沙哈尔这样说自己。</span></font><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
<font face="Times New Roman" size="3">&quot;</font></span><font size="3"><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">在哈佛，我第一次教授积极心理学课时，只有</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">8</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">个学生报名，其中，还有</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">2</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">人中途退课。第二次，我有近</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">400</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">名学生。到了第三次，当学生数目达到</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">850</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">人时，上课更多的是让我感到紧张和不安。特别是当学生的家长、爷爷奶奶和那些媒体的朋友们，开始出现在我课堂上的时侯。</span></font><font size="3"><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">&quot;<br />
</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">塔尔博士毕业于哈佛大学，他拥有心理学硕士、哲学和组织行为学博士学位。他所开设的</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">&quot;</font></span> <span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">积极心理学</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">&quot;</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">和</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">&quot;</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">领袖心理学</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">&quot;</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">，被哈佛学生们推选为最受欢迎率排名第一和第三的课程。选修这两门课程的哈佛学生超过了总人数的</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">20%</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">，其中</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">23%</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">的听课者向学校教学委员会反映：这两门课程</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">&quot;</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">改变了他们的一生</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">&quot;</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">。</span></font><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
</span><font size="3"><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">塔尔博士在哈佛学生中享有很高的声誉，受到学生们的爱戴与敬仰，被誉为</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">&quot;</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">最受欢迎讲师</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">&quot;</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">和</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">&quot;</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">人生导师</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">&quot;</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">。</span></font><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
</span><font size="3"><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">由于他的课程在哈佛大学引起了前所未有的轰动，美国公共广播电台（</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">NPR</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">）、美国有限新闻网（</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">CNN</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">）、美国哥伦比亚广播公司（</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">CBS</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">）、《纽约时报》和《波士顿环球报》等全球数十家著名媒体对他进行了专访和追踪报道。</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">10</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">年来泰勒博士专门从事个人和组织机构的优势开发、自信心，以及领袖力提升的研究。除了教授哈佛大学的课程外，他还受聘为多家著名跨国公司的心理咨询顾问和培训师，他的课程因兼具实用性和可操作性，被企业家和高管们誉为</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">&quot;</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">摸得着幸福</span> <span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">&quot;</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">的心理课程。</span></font><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
</span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'"><font size="3">塔尔&middot;宾－夏哈尔希望他的学生学会接受自己，不要忽略自己所拥有的独特性；</font></span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
</span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'"><font size="3">要摆脱「完美主义」，要「学会失败」。</font></span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
</span><font size="3"><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">塔尔&middot;宾－夏哈尔为学生简化出</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">10</font></span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">条小贴纸：</span></font><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
<font face="Times New Roman" size="3">1.</font></span> <span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'"><font size="3">遵从你内心的热情</font></span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
</span><font size="3"><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">选择对你有意义并且能让你快乐的课，不要只是为了轻松地拿一个</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">A</font></span> <span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">而选课，</span> <span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">或选你朋友上的课，或是别人认为你应该上的课。</span></font><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
<font face="Times New Roman" size="3">2.</font></span> <span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'"><font size="3">多和朋友们在一起</font></span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
</span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'"><font size="3">不要被日常工作缠身，亲密的人际关系，是你幸福感的信号，最有可能为你带来幸福。</font></span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
<font face="Times New Roman" size="3">3.</font></span> <span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'"><font size="3">学会失败</font></span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
</span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'"><font size="3">成功没有捷径，历史上有成就的人，总是敢于行动，也会经常失败。不要让对失败的恐惧，绊住你尝试新事物的脚步。</font></span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
<font face="Times New Roman" size="3">4.</font></span> <span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'"><font size="3">接受自己全然为人</font></span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
</span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'"><font size="3">失望、烦乱、悲伤是人性的一部分。接纳这些，并把它们当成自然之事，允许自己偶尔的失落和伤感。然后问问自己，能做些什么来让自己感觉好过一点。</font></span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
<font face="Times New Roman" size="3">5.</font></span> <span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'"><font size="3">简化生活</font></span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
</span><font size="3"><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">更多并不总代表更好，好事多了，</span> <span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">不一定有利。你选了太多的课吗？参加了太多的活动吗？应求精而不在多。</span></font><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
<font face="Times New Roman" size="3">6.</font></span> <span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'"><font size="3">有规律地锻炼。</font></span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
</span><font size="3"><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">体育运动是你生活中最重要的事情之一。每周只要</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">3</font></span> <span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">次，每次只要</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">30</font></span> <span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">分钟，</span> <span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">就能大大改善你的身心健康。</span></font><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
<font face="Times New Roman" size="3">7.</font></span> <span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'"><font size="3">睡眠</font></span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
</span><font size="3"><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">虽然有时「熬通宵」是不可避免的，但每天</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">7</font></span> <span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">到</span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><font face="Times New Roman">9</font></span> <span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">小时的睡眠是一笔非常棒的投资。这样，在醒着的时候，你会更有效率、更有创造力，也会更开心。</span></font><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
<font face="Times New Roman" size="3">8.</font></span> <span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'"><font size="3">慷慨</font></span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
</span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'"><font size="3">现在，你的钱包里可能没有太多钱，你也没有太多时间。但这并不意味着你无法助人。「给予」和「接受」是一件事的两个面。当我们帮助别人时，我们也在帮助自己；当我们帮助自己时，也是在间接地帮助他人。</font></span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
<font face="Times New Roman" size="3">9.</font></span> <span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'"><font size="3">勇敢</font></span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
</span><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'"><font size="3">勇气并不是不恐惧，而是心怀恐惧，仍依然向前。</font></span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
<font face="Times New Roman" size="3">10.</font></span> <span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'"><font size="3">表达感激</font></span><span lang="EN-US" xml:lang="EN-US" style="font-size: 14pt"><br />
</span><font size="3"><span style="font-size: 14pt; font-family: 宋体; mso-ascii-font-family: 'Times new roman'; mso-hansi-font-family: 'Times new roman'">生活中，不要把你的家人、朋友、健康、教育等这一切当成理所当然的。它们都是你回味无穷的礼物。记录他人的点滴恩惠，始终保持感恩之心。每天或至少每周一次，请你把它们记下来。</span></font></p>
</p>
      <p><a href="/cms/newscontent/contentupload/file/2011-02/596a3f81_c23f_4a05_a5e3_b7c4fb091ae9.ppt" target="_blank">点击下载附件</a></p>
   </div>
   
 </div>

